### ISSUE TITLE
Plugin fails when source base is too big

### ISSUE THREAD

**Issue by eyalroth** [olisikh/gradle-scalastyle-plugin#22]
The plugin doesn't work for module with many files, as the it tries to execute a java command with an argument list too long.

Due to #21, I had to extract the full command from gradle's info output, and indeed I saw that the plugin is trying to execute an extremely long command (260KB long), which prompts the error:
```
/my/path/to/bin/java: Argument list too long
```

**Comment by olisikh** [comment]
Hi Eyal,

Thank you for reporting this, there was a bug related to collecting source files paths for Scalastyle, plugin was collecting paths per each individual *.scala file instead of just root source folder path. 
As the codebase in the project grows, command line would blow eventually.

This issue should not happen in 3.3.1 version of a plugin, could you please verify that?

**Comment by eyalroth** [comment]
Seems to be resolved, thank you!
